// AUTO-GENERATED from pulse_speed_network_troubleshooting_cisco_iosxe_100.csv
// Initial dataset: Cisco IOS/IOS-XE, 100 records. Future vendor CSVs append here.

export interface CookbookCommand {
  id: string;
  vendor: string;
  platform: string;
  os_version_scope: string;
  device_type: string;
  category: string;
  subcategory: string;
  command: string;
  command_mode: string;
  purpose: string;
  when_to_use: string;
  what_to_check: string;
  healthy_indication: string;
  red_flags: string;
  likely_meaning: string;
  next_command: string;
  risk: "Safe" | "Caution" | "Danger";
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  tags: string;
  notes: string;
}

export const COOKBOOK_COMMANDS: CookbookCommand[] = [
  {
    "id": "CIS-IOSXE-001",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Health",
    "subcategory": "System",
    "command": "show version",
    "command_mode": "EXEC",
    "purpose": "Shows platform, software, uptime and hardware summary",
    "when_to_use": "Initial health check",
    "what_to_check": "Version, uptime, model, reload reason",
    "healthy_indication": "Expected software/model and stable uptime",
    "red_flags": "Unexpected reload, old software, resource warnings",
    "likely_meaning": "Possible software/hardware or stability issue",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "health,version,uptime",
    "notes": "Verify exact syntax against platform/release."
  },
  {
    "id": "CIS-IOSXE-002",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Health",
    "subcategory": "CPU",
    "command": "show processes cpu sorted",
    "command_mode": "EXEC",
    "purpose": "Shows CPU utilisation and top processes",
    "when_to_use": "Device slow/high CPU",
    "what_to_check": "5-second/1-minute/5-minute CPU and top process",
    "healthy_indication": "CPU within normal baseline",
    "red_flags": "Sustained high CPU or one process dominating",
    "likely_meaning": "Possible control-plane/software/process issue",
    "next_command": "show processes cpu history",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "cpu,performance",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-003",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Health",
    "subcategory": "Memory",
    "command": "show processes memory sorted",
    "command_mode": "EXEC",
    "purpose": "Shows memory usage by process",
    "when_to_use": "Memory alarms or instability",
    "what_to_check": "Used/free memory and top consumers",
    "healthy_indication": "Adequate free memory",
    "red_flags": "Very low free memory or abnormal process growth",
    "likely_meaning": "Memory pressure/leak/configuration issue",
    "next_command": "show memory statistics",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "memory,performance",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-004",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Logs",
    "subcategory": "System",
    "command": "show logging",
    "command_mode": "EXEC",
    "purpose": "Displays buffered system logs",
    "when_to_use": "After an outage or interface event",
    "what_to_check": "Link flaps, errors, protocol events, reloads",
    "healthy_indication": "No unexpected critical events",
    "red_flags": "Repeated link/protocol errors",
    "likely_meaning": "Correlate event time with affected service",
    "next_command": "show interfaces",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "logs,syslog",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-005",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Configuration",
    "subcategory": "Running Config",
    "command": "show running-config",
    "command_mode": "EXEC",
    "purpose": "Displays active configuration",
    "when_to_use": "Verify how a feature is configured",
    "what_to_check": "Relevant interface, routing, ACL, VLAN config",
    "healthy_indication": "Configuration matches intended design",
    "red_flags": "Unexpected commands or missing configuration",
    "likely_meaning": "Configuration drift or wrong feature settings",
    "next_command": "show startup-config",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "configuration",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-006",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Configuration",
    "subcategory": "Startup Config",
    "command": "show startup-config",
    "command_mode": "EXEC",
    "purpose": "Displays saved configuration",
    "when_to_use": "After reboot/configuration issue",
    "what_to_check": "Compare with running configuration",
    "healthy_indication": "Expected config is saved",
    "red_flags": "Running config differs from startup",
    "likely_meaning": "Unsaved changes or stale config",
    "next_command": "show running-config",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "configuration,backup",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-007",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Summary",
    "command": "show ip interface brief",
    "command_mode": "EXEC",
    "purpose": "Quick IP/interface state summary",
    "when_to_use": "First check for interface problems",
    "what_to_check": "Status, protocol, IP, admin state",
    "healthy_indication": "Expected interfaces up/up",
    "red_flags": "down/down, administratively down, wrong IP",
    "likely_meaning": "Physical, VLAN, protocol or configuration issue",
    "next_command": "show interfaces",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,status",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-008",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Detail",
    "command": "show interfaces <interface>",
    "command_mode": "EXEC",
    "purpose": "Detailed interface counters and state",
    "when_to_use": "Connectivity, errors or performance issues",
    "what_to_check": "CRC, input/output errors, drops, resets, speed, duplex, rates",
    "healthy_indication": "Up/up with stable counters and expected speed",
    "red_flags": "CRC/errors/drops/resets or unexpected speed",
    "likely_meaning": "Physical, optic, congestion or remote-end issue",
    "next_command": "show interfaces counters errors",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,errors,crc",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-009",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Errors",
    "command": "show interfaces counters errors",
    "command_mode": "EXEC",
    "purpose": "Summarises interface error counters",
    "when_to_use": "Quickly identify bad ports",
    "what_to_check": "CRC, runts, giants, input/output errors",
    "healthy_indication": "Counters zero/stable",
    "red_flags": "Increasing errors",
    "likely_meaning": "Physical/link or framing issue",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,errors",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-010",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Status",
    "command": "show interfaces status",
    "command_mode": "EXEC",
    "purpose": "Port status, VLAN, speed and duplex summary",
    "when_to_use": "Switch port troubleshooting",
    "what_to_check": "Connected/notconnect, VLAN, duplex, speed",
    "healthy_indication": "Expected state and VLAN",
    "red_flags": "Wrong VLAN, speed/duplex, err-disabled",
    "likely_meaning": "Port configuration or physical issue",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "switchport,interface",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-011",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Transceiver",
    "command": "show interfaces transceiver",
    "command_mode": "EXEC",
    "purpose": "Displays optic/transceiver information",
    "when_to_use": "Optical link or optic issue",
    "what_to_check": "DOM/optic type and levels where supported",
    "healthy_indication": "Optic present and levels within vendor limits",
    "red_flags": "Missing optic, abnormal levels, unsupported optic",
    "likely_meaning": "Optic/cabling compatibility or optical power issue",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "optic,transceiver",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-012",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Counters",
    "command": "show interfaces counters",
    "command_mode": "EXEC",
    "purpose": "Shows interface traffic counters",
    "when_to_use": "Traffic/counter comparison",
    "what_to_check": "Packets, bytes, errors",
    "healthy_indication": "Expected traffic pattern",
    "red_flags": "Unexpected zero traffic or errors",
    "likely_meaning": "Path/configuration/physical issue",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,counters",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-013",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "MAC Table",
    "command": "show mac address-table",
    "command_mode": "EXEC",
    "purpose": "Displays learned MAC addresses",
    "when_to_use": "Host connectivity or MAC learning issue",
    "what_to_check": "MAC, VLAN, port",
    "healthy_indication": "Expected MAC learned on expected port",
    "red_flags": "MAC missing or learned on wrong port",
    "likely_meaning": "VLAN, link, STP, endpoint or loop issue",
    "next_command": "show mac address-table dynamic",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "mac,vlan,layer2",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-014",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "MAC by Port",
    "command": "show mac address-table interface <interface>",
    "command_mode": "EXEC",
    "purpose": "Shows MACs learned on a port",
    "when_to_use": "Check whether endpoint is learned",
    "what_to_check": "MAC/VLAN/interface",
    "healthy_indication": "Expected endpoint MAC present",
    "red_flags": "No MAC or unexpected MAC",
    "likely_meaning": "Link/VLAN/endpoint or possible loop/security issue",
    "next_command": "show interfaces status",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "mac,interface",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-015",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "VLAN",
    "subcategory": "VLAN Summary",
    "command": "show vlan brief",
    "command_mode": "EXEC",
    "purpose": "Shows VLANs and access-port membership",
    "when_to_use": "Host cannot communicate within VLAN",
    "what_to_check": "VLAN exists and port membership",
    "healthy_indication": "Correct VLAN active",
    "red_flags": "Missing VLAN or wrong access VLAN",
    "likely_meaning": "VLAN/configuration issue",
    "next_command": "show interfaces switchport",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "vlan,access-port",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-016",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "VLAN",
    "subcategory": "Switchport",
    "command": "show interfaces <interface> switchport",
    "command_mode": "EXEC",
    "purpose": "Displays switchport mode and VLAN details",
    "when_to_use": "Access/trunk mismatch",
    "what_to_check": "Administrative/operational mode, access VLAN, trunk VLANs",
    "healthy_indication": "Expected mode and VLAN",
    "red_flags": "Wrong mode/VLAN, unexpected trunking",
    "likely_meaning": "Layer-2 configuration mismatch",
    "next_command": "show interfaces trunk",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "switchport,trunk,vlan",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-017",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "VLAN",
    "subcategory": "Trunk",
    "command": "show interfaces trunk",
    "command_mode": "EXEC",
    "purpose": "Shows trunk ports and allowed/active VLANs",
    "when_to_use": "Inter-VLAN/site VLAN problem",
    "what_to_check": "Native VLAN, allowed VLANs, active VLANs",
    "healthy_indication": "Expected VLANs allowed and active",
    "red_flags": "VLAN missing from allowed/active list",
    "likely_meaning": "Trunk/VLAN configuration issue",
    "next_command": "show interfaces <interface> switchport",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "trunk,vlan",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-018",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "STP",
    "subcategory": "Summary",
    "command": "show spanning-tree summary",
    "command_mode": "EXEC",
    "purpose": "Summarises STP mode and status",
    "when_to_use": "Loop/STP investigation",
    "what_to_check": "STP mode, root information, inconsistent states",
    "healthy_indication": "Expected root and stable topology",
    "red_flags": "Unexpected root, topology changes, inconsistencies",
    "likely_meaning": "STP topology/configuration issue",
    "next_command": "show spanning-tree",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "stp,loop",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-019",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "STP",
    "subcategory": "Interface",
    "command": "show spanning-tree interface <interface> detail",
    "command_mode": "EXEC",
    "purpose": "Shows STP state and events for an interface",
    "when_to_use": "Port forwarding/blocking issue",
    "what_to_check": "Role, state, cost, transitions, BPDU details",
    "healthy_indication": "Expected forwarding state",
    "red_flags": "Blocking/discarding, frequent transitions",
    "likely_meaning": "STP topology or loop issue",
    "next_command": "show spanning-tree vlan <vlan>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "stp,interface",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-020",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "STP",
    "subcategory": "VLAN",
    "command": "show spanning-tree vlan <vlan>",
    "command_mode": "EXEC",
    "purpose": "Shows STP topology for a VLAN",
    "when_to_use": "Determine root and port roles",
    "what_to_check": "Root bridge, root port, designated ports",
    "healthy_indication": "Expected root and forwarding path",
    "red_flags": "Unexpected root/blocking port",
    "likely_meaning": "STP design or link issue",
    "next_command": "show spanning-tree interface <interface> detail",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "stp,vlan",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-021",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Discovery",
    "subcategory": "CDP",
    "command": "show cdp neighbors detail",
    "command_mode": "EXEC",
    "purpose": "Displays directly connected Cisco neighbors",
    "when_to_use": "Identify physical topology",
    "what_to_check": "Neighbor device, local/remote port, IP",
    "healthy_indication": "Expected neighbor and port",
    "red_flags": "Unexpected/missing neighbor",
    "likely_meaning": "Physical, CDP or topology issue",
    "next_command": "show lldp neighbors detail",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "cdp,topology",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-022",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Discovery",
    "subcategory": "LLDP",
    "command": "show lldp neighbors detail",
    "command_mode": "EXEC",
    "purpose": "Displays LLDP neighbors",
    "when_to_use": "Multi-vendor topology verification",
    "what_to_check": "Neighbor, port, capabilities",
    "healthy_indication": "Expected neighbor",
    "red_flags": "Missing/unexpected neighbor",
    "likely_meaning": "Physical/link/discovery issue",
    "next_command": "show interfaces status",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "lldp,topology",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-023",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "LACP",
    "subcategory": "EtherChannel",
    "command": "show etherchannel summary",
    "command_mode": "EXEC",
    "purpose": "Summarises port-channel/LACP state",
    "when_to_use": "Port-channel failure or degraded bundle",
    "what_to_check": "Port-channel state, member ports, protocols",
    "healthy_indication": "Members bundled and channel up",
    "red_flags": "Suspended, individual, down or missing members",
    "likely_meaning": "LACP/configuration/physical mismatch",
    "next_command": "show interfaces port-channel <id>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "lacp,etherchannel",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-024",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "LACP",
    "subcategory": "Port Channel",
    "command": "show interfaces port-channel <id>",
    "command_mode": "EXEC",
    "purpose": "Detailed port-channel status",
    "when_to_use": "Traffic/path issue over bundle",
    "what_to_check": "Protocol, line state, counters",
    "healthy_indication": "Expected members and traffic",
    "red_flags": "Errors, drops or down state",
    "likely_meaning": "Bundle/member problem",
    "next_command": "show etherchannel summary",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "lacp,port-channel",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-025",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "PoE",
    "subcategory": "PoE Status",
    "command": "show power inline",
    "command_mode": "EXEC",
    "purpose": "Shows PoE delivery and status",
    "when_to_use": "AP/phone/camera has no power",
    "what_to_check": "Power allocated, drawn, status",
    "healthy_indication": "Device powered with expected wattage",
    "red_flags": "Denied, faulty, insufficient budget",
    "likely_meaning": "PoE budget, cable, port or endpoint issue",
    "next_command": "show power inline <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "poe,wireless,phone",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-026",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "ARP",
    "command": "show ip arp",
    "command_mode": "EXEC",
    "purpose": "Displays IP-to-MAC mappings",
    "when_to_use": "Local reachability problem",
    "what_to_check": "IP, MAC, age, interface",
    "healthy_indication": "Expected mapping exists",
    "red_flags": "Incomplete/missing/unexpected MAC",
    "likely_meaning": "ARP, VLAN, endpoint or L2 issue",
    "next_command": "show mac address-table",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "arp,layer3",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-027",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "Route Table",
    "command": "show ip route",
    "command_mode": "EXEC",
    "purpose": "Displays routing table",
    "when_to_use": "Destination unreachable or path verification",
    "what_to_check": "Route, next-hop, protocol, AD/metric",
    "healthy_indication": "Expected route and next-hop",
    "red_flags": "Missing or unexpected route",
    "likely_meaning": "Routing/configuration/policy issue",
    "next_command": "show ip route <destination>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "routing,route",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-028",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "Specific Route",
    "command": "show ip route <destination>",
    "command_mode": "EXEC",
    "purpose": "Shows route lookup for a destination",
    "when_to_use": "Determine exact forwarding path",
    "what_to_check": "Longest match, next-hop, outgoing interface",
    "healthy_indication": "Expected next-hop/interface",
    "red_flags": "No route or wrong path",
    "likely_meaning": "Routing table or route-policy issue",
    "next_command": "show ip cef <destination>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "routing,path",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-029",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "CEF",
    "command": "show ip cef <destination>",
    "command_mode": "EXEC",
    "purpose": "Shows Cisco Express Forwarding entry",
    "when_to_use": "Verify forwarding decision",
    "what_to_check": "Prefix, adjacency, next-hop",
    "healthy_indication": "Expected forwarding adjacency",
    "red_flags": "Drop/null/glean/unexpected adjacency",
    "likely_meaning": "CEF/ARP/path issue",
    "next_command": "show adjacency",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "cef,forwarding",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-030",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "Interface IP",
    "command": "show ip interface <interface>",
    "command_mode": "EXEC",
    "purpose": "Shows IP settings and features on interface",
    "when_to_use": "IP interface/ACL/redirect issue",
    "what_to_check": "IP address, access groups, redirects, helper",
    "healthy_indication": "Expected IP/features",
    "red_flags": "Wrong IP, ACL or helper",
    "likely_meaning": "Interface configuration issue",
    "next_command": "show running-config interface <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "ip-interface,acl",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-031",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Routing",
    "subcategory": "Protocols",
    "command": "show ip protocols",
    "command_mode": "EXEC",
    "purpose": "Shows routing protocol configuration and sources",
    "when_to_use": "Route missing from dynamic protocol",
    "what_to_check": "Networks, neighbors, redistribution, filters",
    "healthy_indication": "Expected protocol/configuration",
    "red_flags": "Missing network, unexpected redistribution/filter",
    "likely_meaning": "Routing protocol configuration issue",
    "next_command": "show ip route",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "routing,protocols",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-032",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "OSPF Neighbors",
    "command": "show ip ospf neighbor",
    "command_mode": "EXEC",
    "purpose": "Shows OSPF adjacency states",
    "when_to_use": "OSPF route/neighbor issue",
    "what_to_check": "Neighbor state, RID, interface, dead timer",
    "healthy_indication": "FULL where expected",
    "red_flags": "Down/Init/2-Way/ExStart/Exchange stuck",
    "likely_meaning": "L2, timers, MTU, network type, auth or topology issue",
    "next_command": "show ip ospf interface",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ospf,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-033",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "OSPF Interface",
    "command": "show ip ospf interface <interface>",
    "command_mode": "EXEC",
    "purpose": "Shows OSPF interface parameters",
    "when_to_use": "Adjacency not forming",
    "what_to_check": "Area, network type, timers, cost, auth",
    "healthy_indication": "Matches peer/design",
    "red_flags": "Timer/network-type/area mismatch",
    "likely_meaning": "OSPF interface configuration mismatch",
    "next_command": "show ip ospf neighbor",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ospf,interface",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-034",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "OSPF Process",
    "command": "show ip ospf",
    "command_mode": "EXEC",
    "purpose": "Shows OSPF process/area information",
    "when_to_use": "General OSPF health",
    "what_to_check": "Router ID, areas, SPF stats",
    "healthy_indication": "Expected process and areas",
    "red_flags": "Unexpected area/RID or repeated SPF events",
    "likely_meaning": "OSPF process/topology issue",
    "next_command": "show ip ospf database",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ospf",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-035",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "OSPF Database",
    "command": "show ip ospf database",
    "command_mode": "EXEC",
    "purpose": "Shows OSPF LSDB",
    "when_to_use": "Route/topology mismatch",
    "what_to_check": "LSAs and originating routers",
    "healthy_indication": "Expected LSAs present",
    "red_flags": "Missing/stale/unexpected LSAs",
    "likely_meaning": "Adjacency/flooding/redistribution issue",
    "next_command": "show ip ospf neighbor",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "ospf,lsdb",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-036",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "BGP Summary",
    "command": "show ip bgp summary",
    "command_mode": "EXEC",
    "purpose": "Shows BGP peer/session status and prefixes",
    "when_to_use": "BGP neighbor or route issue",
    "what_to_check": "Neighbor state, Up/Down, State/PfxRcd",
    "healthy_indication": "Established with expected prefix count",
    "red_flags": "Idle/Active/Connect or unexpected prefix count",
    "likely_meaning": "TCP, peer config, policy, reachability or authentication issue",
    "next_command": "show ip bgp neighbors <neighbor>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "bgp,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-037",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "BGP Table",
    "command": "show ip bgp",
    "command_mode": "EXEC",
    "purpose": "Displays BGP routing table",
    "when_to_use": "Specific prefix/path selection issue",
    "what_to_check": "Paths, next-hop, best path, AS path",
    "healthy_indication": "Expected path selected",
    "red_flags": "No path, wrong best path, inaccessible next-hop",
    "likely_meaning": "Policy, attributes or reachability issue",
    "next_command": "show ip bgp <prefix>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "bgp,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-038",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "BGP Prefix",
    "command": "show ip bgp <prefix>",
    "command_mode": "EXEC",
    "purpose": "Shows BGP paths for one prefix",
    "when_to_use": "Find why a route is or isn't selected",
    "what_to_check": "Best path, attributes, next-hop",
    "healthy_indication": "Expected path is best/valid",
    "red_flags": "Rejected/inaccessible/less-preferred path",
    "likely_meaning": "Policy/attribute/next-hop issue",
    "next_command": "show ip bgp neighbors <neighbor>",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "bgp,path-selection",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-039",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "BGP Neighbor",
    "command": "show ip bgp neighbors <neighbor>",
    "command_mode": "EXEC",
    "purpose": "Detailed BGP/TCP/policy information",
    "when_to_use": "Peer-specific troubleshooting",
    "what_to_check": "Session, capabilities, received/advertised routes, policy",
    "healthy_indication": "Session established and expected routes",
    "red_flags": "Session resets, filters, missing routes",
    "likely_meaning": "BGP session or policy issue",
    "next_command": "show ip bgp summary",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "bgp,neighbor",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-040",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "BGP Advertised",
    "command": "show ip bgp neighbors <neighbor> advertised-routes",
    "command_mode": "EXEC",
    "purpose": "Shows routes advertised to a BGP peer",
    "when_to_use": "Remote peer missing expected route",
    "what_to_check": "Advertised prefixes",
    "healthy_indication": "Expected prefix present",
    "red_flags": "Prefix absent",
    "likely_meaning": "Outbound policy/network statement/route issue",
    "next_command": "show ip route <prefix>",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "bgp,policy",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-041",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Security",
    "subcategory": "ACL",
    "command": "show access-lists",
    "command_mode": "EXEC",
    "purpose": "Displays ACL entries and hit counters",
    "when_to_use": "Traffic blocked or policy verification",
    "what_to_check": "Permit/deny entries and counters",
    "healthy_indication": "Expected rule hit",
    "red_flags": "Unexpected deny or no expected hit",
    "likely_meaning": "ACL ordering/match/source/destination issue",
    "next_command": "show ip interface <interface>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "acl,security",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-042",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "NAT",
    "subcategory": "NAT Translations",
    "command": "show ip nat translations",
    "command_mode": "EXEC",
    "purpose": "Shows active NAT translations",
    "when_to_use": "NAT/Internet access issue",
    "what_to_check": "Inside/outside addresses and ports",
    "healthy_indication": "Expected translation exists",
    "red_flags": "No translation or wrong mapping",
    "likely_meaning": "NAT rule, route or traffic initiation issue",
    "next_command": "show ip nat statistics",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "nat,translation",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-043",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "NAT",
    "subcategory": "NAT Statistics",
    "command": "show ip nat statistics",
    "command_mode": "EXEC",
    "purpose": "Shows NAT counters and configuration summary",
    "when_to_use": "NAT troubleshooting",
    "what_to_check": "Hits, misses, interfaces, pool usage",
    "healthy_indication": "Counters increase as traffic passes",
    "red_flags": "No translations/hits or pool exhaustion",
    "likely_meaning": "NAT classification/rule/pool issue",
    "next_command": "show ip nat translations",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "nat,statistics",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-044",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "DHCP",
    "subcategory": "Bindings",
    "command": "show ip dhcp binding",
    "command_mode": "EXEC",
    "purpose": "Shows DHCP leases",
    "when_to_use": "Client DHCP issue",
    "what_to_check": "Client IP/MAC/lease",
    "healthy_indication": "Expected lease exists",
    "red_flags": "Missing/stale/unexpected lease",
    "likely_meaning": "DHCP scope/client/VLAN issue",
    "next_command": "show ip dhcp pool",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "dhcp",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-045",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "DHCP",
    "subcategory": "Pool",
    "command": "show ip dhcp pool",
    "command_mode": "EXEC",
    "purpose": "Shows DHCP pool utilisation",
    "when_to_use": "DHCP exhaustion",
    "what_to_check": "Used/free addresses",
    "healthy_indication": "Adequate free leases",
    "red_flags": "Pool exhausted",
    "likely_meaning": "DHCP scope sizing/exclusions/client churn",
    "next_command": "show ip dhcp binding",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "dhcp,pool",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-046",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Diagnostics",
    "subcategory": "Ping",
    "command": "ping <destination>",
    "command_mode": "EXEC",
    "purpose": "Tests IP reachability",
    "when_to_use": "Basic connectivity check",
    "what_to_check": "Success rate and latency",
    "healthy_indication": "Expected replies",
    "red_flags": "Loss/unreachable/high latency",
    "likely_meaning": "Layered path problem; continue with route/ARP/interface checks",
    "next_command": "traceroute <destination>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "ping,connectivity",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-047",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Diagnostics",
    "subcategory": "Extended Ping",
    "command": "ping",
    "command_mode": "EXEC",
    "purpose": "Interactive ping with source/options",
    "when_to_use": "Test specific source/VRF/path",
    "what_to_check": "Source address, repeat count, size",
    "healthy_indication": "Expected reachability from chosen source",
    "red_flags": "Failure only from specific source",
    "likely_meaning": "VRF/routing/ACL/asymmetric path issue",
    "next_command": "show ip route <destination>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ping,source",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-048",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Diagnostics",
    "subcategory": "Traceroute",
    "command": "traceroute <destination>",
    "command_mode": "EXEC",
    "purpose": "Shows Layer-3 path hop by hop",
    "when_to_use": "Find path break or unexpected routing",
    "what_to_check": "Hop sequence and where responses stop",
    "healthy_indication": "Expected path",
    "red_flags": "Timeouts or unexpected detour",
    "likely_meaning": "Routing/ACL/firewall/TTL response issue",
    "next_command": "show ip route <destination>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "traceroute,path",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-049",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Diagnostics",
    "subcategory": "VRF Ping",
    "command": "ping vrf <vrf> <destination>",
    "command_mode": "EXEC",
    "purpose": "Tests reachability inside a VRF",
    "when_to_use": "VRF-specific connectivity issue",
    "what_to_check": "VRF/source/path",
    "healthy_indication": "Expected VRF reachability",
    "red_flags": "No response or wrong VRF",
    "likely_meaning": "VRF route/import/export/ACL issue",
    "next_command": "show ip route vrf <vrf>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "vrf,ping",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-050",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Diagnostics",
    "subcategory": "VRF Route",
    "command": "show ip route vrf <vrf>",
    "command_mode": "EXEC",
    "purpose": "Displays a VRF routing table",
    "when_to_use": "VRF destination unreachable",
    "what_to_check": "Route and next-hop within VRF",
    "healthy_indication": "Expected route present",
    "red_flags": "Missing/wrong route",
    "likely_meaning": "VRF routing or route-leaking issue",
    "next_command": "show ip cef vrf <vrf> <destination>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "vrf,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-051",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "STP Detail",
    "command": "show spanning-tree detail",
    "command_mode": "EXEC",
    "purpose": "Shows STP topology-change details",
    "when_to_use": "Frequent topology changes",
    "what_to_check": "Change counters and last change",
    "healthy_indication": "Stable counters",
    "red_flags": "Rapid/increasing changes",
    "likely_meaning": "Flapping links, endpoint movement or loop",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "stp,topology-change",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-052",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "Errdisable",
    "command": "show interfaces status err-disabled",
    "command_mode": "EXEC",
    "purpose": "Lists err-disabled interfaces",
    "when_to_use": "Port unexpectedly disabled",
    "what_to_check": "Port and reason where supported",
    "healthy_indication": "No unexpected err-disabled ports",
    "red_flags": "Ports in err-disabled state",
    "likely_meaning": "BPDU guard, link-flap, security or other protection trigger",
    "next_command": "show errdisable recovery",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "errdisable,switching",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-053",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "Errdisable Recovery",
    "command": "show errdisable recovery",
    "command_mode": "EXEC",
    "purpose": "Shows err-disable recovery settings/status",
    "when_to_use": "Port recovery issue",
    "what_to_check": "Reason, timer, status",
    "healthy_indication": "Expected protection settings",
    "red_flags": "Unexpected disabled reason or recovery behavior",
    "likely_meaning": "Protection feature triggered",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "errdisable",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-054",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "Interface Description",
    "command": "show interfaces description",
    "command_mode": "EXEC",
    "purpose": "Shows interface descriptions and status",
    "when_to_use": "Map physical/logical connections quickly",
    "what_to_check": "Status/protocol/description",
    "healthy_indication": "Expected link states",
    "red_flags": "Unexpected down/up mismatch",
    "likely_meaning": "Physical or configuration issue",
    "next_command": "show cdp neighbors",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,documentation",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-055",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "MAC Dynamic",
    "command": "show mac address-table dynamic",
    "command_mode": "EXEC",
    "purpose": "Shows dynamically learned MACs",
    "when_to_use": "MAC learning/loop investigation",
    "what_to_check": "VLAN, MAC, port, type",
    "healthy_indication": "Expected dynamic entries",
    "red_flags": "MAC moves/flapping or missing entries",
    "likely_meaning": "Loop, endpoint movement or VLAN issue",
    "next_command": "show spanning-tree",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "mac,flap",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-056",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "MAC Move",
    "command": "show mac address-table notification mac-move",
    "command_mode": "EXEC",
    "purpose": "Shows MAC-move notification settings where supported",
    "when_to_use": "MAC flapping investigation",
    "what_to_check": "Notification/configuration",
    "healthy_indication": "Expected monitoring configuration",
    "red_flags": "Frequent MAC movement in logs",
    "likely_meaning": "Loop or dual attachment",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "mac,flap,loop",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-057",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "Storm Control",
    "command": "show storm-control",
    "command_mode": "EXEC",
    "purpose": "Shows storm-control state/counters where supported",
    "when_to_use": "Broadcast/multicast storm issue",
    "what_to_check": "Thresholds and dropped packets",
    "healthy_indication": "No abnormal drops",
    "red_flags": "High drop counters or storm state",
    "likely_meaning": "Broadcast/multicast storm or loop",
    "next_command": "show interfaces counters errors",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "storm-control,broadcast",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-058",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "QoS",
    "subcategory": "QoS Interface",
    "command": "show policy-map interface <interface>",
    "command_mode": "EXEC",
    "purpose": "Shows QoS policy statistics",
    "when_to_use": "Performance/congestion/QoS issue",
    "what_to_check": "Class counters, drops, rates",
    "healthy_indication": "Expected classes and low drops",
    "red_flags": "High drops in class",
    "likely_meaning": "QoS congestion/classification issue",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "qos,drops",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-059",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "QoS",
    "subcategory": "Policy Map",
    "command": "show policy-map",
    "command_mode": "EXEC",
    "purpose": "Displays configured QoS policies",
    "when_to_use": "Verify policy configuration",
    "what_to_check": "Classes/actions",
    "healthy_indication": "Expected policy",
    "red_flags": "Unexpected class/action",
    "likely_meaning": "QoS configuration mismatch",
    "next_command": "show policy-map interface <interface>",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "qos",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-060",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Security",
    "subcategory": "AAA",
    "command": "show aaa servers",
    "command_mode": "EXEC",
    "purpose": "Shows AAA server status where supported",
    "when_to_use": "Authentication/authorization issue",
    "what_to_check": "Server state, counters",
    "healthy_indication": "AAA servers reachable/active",
    "red_flags": "Dead/unreachable server",
    "likely_meaning": "AAA reachability/configuration issue",
    "next_command": "show running-config | section aaa",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "aaa,authentication",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-061",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "OSPF Routes",
    "command": "show ip route ospf",
    "command_mode": "EXEC",
    "purpose": "Shows routes learned through OSPF",
    "when_to_use": "OSPF route missing",
    "what_to_check": "Expected prefixes and next-hops",
    "healthy_indication": "Expected route present",
    "red_flags": "Missing/unexpected OSPF route",
    "likely_meaning": "Adjacency/LSA/redistribution issue",
    "next_command": "show ip ospf database",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ospf,routes",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-062",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "BGP Routes",
    "command": "show ip route bgp",
    "command_mode": "EXEC",
    "purpose": "Shows routes installed from BGP",
    "when_to_use": "BGP route not in RIB",
    "what_to_check": "Installed prefixes and next-hops",
    "healthy_indication": "Expected BGP routes installed",
    "red_flags": "BGP path exists but not installed",
    "likely_meaning": "Next-hop/AD/policy/RIB conflict",
    "next_command": "show ip bgp <prefix>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "bgp,rib",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-063",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "EIGRP Neighbors",
    "command": "show ip eigrp neighbors",
    "command_mode": "EXEC",
    "purpose": "Shows EIGRP adjacencies",
    "when_to_use": "EIGRP route/neighbor issue",
    "what_to_check": "Neighbor uptime, interface, hold time",
    "healthy_indication": "Expected neighbors stable",
    "red_flags": "Missing/flapping neighbor",
    "likely_meaning": "L2, K-values, authentication, AS or interface issue",
    "next_command": "show ip eigrp interfaces",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "eigrp,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-064",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "EIGRP Interfaces",
    "command": "show ip eigrp interfaces",
    "command_mode": "EXEC",
    "purpose": "Shows EIGRP-enabled interfaces",
    "when_to_use": "EIGRP not forming",
    "what_to_check": "Interfaces, AS, peers",
    "healthy_indication": "Expected interfaces enabled",
    "red_flags": "Missing/wrong interface",
    "likely_meaning": "EIGRP configuration issue",
    "next_command": "show ip eigrp neighbors",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "eigrp",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-065",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Routing",
    "subcategory": "EIGRP Topology",
    "command": "show ip eigrp topology",
    "command_mode": "EXEC",
    "purpose": "Shows EIGRP topology and feasible successors",
    "when_to_use": "Route selection/failover issue",
    "what_to_check": "Successor, feasible successor, metrics",
    "healthy_indication": "Expected successor",
    "red_flags": "Active route or missing feasible successor",
    "likely_meaning": "EIGRP convergence/topology issue",
    "next_command": "show ip eigrp neighbors",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "eigrp,topology",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-066",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Security",
    "subcategory": "Interface ACL",
    "command": "show ip interface <interface>",
    "command_mode": "EXEC",
    "purpose": "Shows ACLs applied to an IP interface",
    "when_to_use": "Traffic unexpectedly blocked",
    "what_to_check": "Inbound/outbound access groups",
    "healthy_indication": "Expected ACL attachment",
    "red_flags": "Unexpected ACL",
    "likely_meaning": "ACL application issue",
    "next_command": "show access-lists",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "acl,interface",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-067",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Security",
    "subcategory": "IPsec SA",
    "command": "show crypto ipsec sa",
    "command_mode": "EXEC",
    "purpose": "Shows IPsec security associations and counters",
    "when_to_use": "VPN up/no traffic or tunnel issue",
    "what_to_check": "Encaps/decaps, selectors, peer",
    "healthy_indication": "Counters increase with traffic",
    "red_flags": "No encaps/decaps or selector mismatch",
    "likely_meaning": "Routing, crypto selector or peer issue",
    "next_command": "show crypto isakmp sa",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "ipsec,vpn",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-068",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Security",
    "subcategory": "IKEv1 SA",
    "command": "show crypto isakmp sa",
    "command_mode": "EXEC",
    "purpose": "Shows IKEv1 security associations",
    "when_to_use": "IPsec tunnel establishment issue",
    "what_to_check": "State and peer",
    "healthy_indication": "QM_IDLE/expected established state",
    "red_flags": "MM_* stuck/down",
    "likely_meaning": "IKE policy, PSK, peer reachability or NAT issue",
    "next_command": "show crypto ipsec sa",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "ike,ipsec,vpn",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-069",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Security",
    "subcategory": "IKEv2 SA",
    "command": "show crypto ikev2 sa",
    "command_mode": "EXEC",
    "purpose": "Shows IKEv2 security associations",
    "when_to_use": "IKEv2 VPN issue",
    "what_to_check": "SA state, peer, local/remote",
    "healthy_indication": "Established as expected",
    "red_flags": "No SA or failed state",
    "likely_meaning": "IKEv2 policy/credentials/reachability issue",
    "next_command": "show crypto ipsec sa",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "ikev2,ipsec,vpn",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-070",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Diagnostics",
    "subcategory": "Packet Capture",
    "command": "monitor capture <name> interface <interface> both",
    "command_mode": "EXEC/config context",
    "purpose": "Starts an embedded packet capture on supported platforms",
    "when_to_use": "Need packet-level evidence",
    "what_to_check": "Packets matching capture filters",
    "healthy_indication": "Expected packets visible",
    "red_flags": "Packets absent or unexpected flags",
    "likely_meaning": "Path/ACL/NAT/application issue",
    "next_command": "show monitor capture <name> buffer brief",
    "risk": "Caution",
    "difficulty": "Advanced",
    "tags": "packet-capture,pcap",
    "notes": "Syntax and feature support vary by IOS-XE release/platform."
  },
  {
    "id": "CIS-IOSXE-071",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Diagnostics",
    "subcategory": "Capture Status",
    "command": "show monitor capture <name>",
    "command_mode": "EXEC",
    "purpose": "Shows embedded capture status/details",
    "when_to_use": "Verify capture before/after collection",
    "what_to_check": "Interface, filter, state, buffer",
    "healthy_indication": "Capture active and matching intended scope",
    "red_flags": "Wrong interface/filter or inactive capture",
    "likely_meaning": "Capture setup issue",
    "next_command": "show monitor capture <name> buffer brief",
    "risk": "Safe",
    "difficulty": "Advanced",
    "tags": "packet-capture",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-072",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router",
    "category": "Diagnostics",
    "subcategory": "Debug IP Packet",
    "command": "debug ip packet",
    "command_mode": "EXEC",
    "purpose": "Debugs IP packets subject to configured ACL where supported",
    "when_to_use": "Deep packet troubleshooting",
    "what_to_check": "Packet processing output",
    "healthy_indication": "Only controlled test traffic",
    "red_flags": "Huge output/CPU impact",
    "likely_meaning": "Packet handling/path issue",
    "next_command": "undebug all",
    "risk": "Danger",
    "difficulty": "Advanced",
    "tags": "debug,packet",
    "notes": "Use only with tight filters/ACLs and controlled windows."
  },
  {
    "id": "CIS-IOSXE-073",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Router/Switch",
    "category": "Diagnostics",
    "subcategory": "Debug Disable",
    "command": "undebug all",
    "command_mode": "EXEC",
    "purpose": "Stops active debug processes",
    "when_to_use": "Always after debug work",
    "what_to_check": "Active debug state",
    "healthy_indication": "No unwanted debug running",
    "red_flags": "Continued debug output",
    "likely_meaning": "Unstopped debug can affect device",
    "next_command": "show debugging",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "debug,safety",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-074",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Diagnostics",
    "subcategory": "Debug State",
    "command": "show debugging",
    "command_mode": "EXEC",
    "purpose": "Shows active debug commands",
    "when_to_use": "Before/after debug troubleshooting",
    "what_to_check": "Which debugs are active",
    "healthy_indication": "Only intended debug active",
    "red_flags": "Unexpected active debug",
    "likely_meaning": "Potential CPU/log impact",
    "next_command": "undebug all",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "debug",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-075",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Hardware",
    "subcategory": "Inventory",
    "command": "show inventory",
    "command_mode": "EXEC",
    "purpose": "Displays hardware modules and serial information",
    "when_to_use": "Hardware/optic/module identification",
    "what_to_check": "PID, VID, serial, modules",
    "healthy_indication": "Expected hardware present",
    "red_flags": "Missing/unsupported module",
    "likely_meaning": "Hardware/module issue",
    "next_command": "show environment all",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "hardware,inventory",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-076",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Hardware",
    "subcategory": "Environment",
    "command": "show environment all",
    "command_mode": "EXEC",
    "purpose": "Shows temperature, fans, power and environmental status where supported",
    "when_to_use": "Hardware health/overheating",
    "what_to_check": "Temperature, fans, power",
    "healthy_indication": "All sensors normal",
    "red_flags": "Critical temperature/fan/power alarm",
    "likely_meaning": "Hardware/environment issue",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "hardware,temperature,power",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-077",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Hardware",
    "subcategory": "Flash",
    "command": "dir flash:",
    "command_mode": "EXEC",
    "purpose": "Lists files in flash storage",
    "when_to_use": "Image/config/file issue",
    "what_to_check": "Available space and image files",
    "healthy_indication": "Sufficient space and expected image",
    "red_flags": "Low space/missing image",
    "likely_meaning": "Storage/image/configuration issue",
    "next_command": "show version",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "flash,storage",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-078",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Hardware",
    "subcategory": "Boot Variables",
    "command": "show bootvar",
    "command_mode": "EXEC",
    "purpose": "Shows boot image/config variables where supported",
    "when_to_use": "Unexpected image after reboot",
    "what_to_check": "Boot variable and config register",
    "healthy_indication": "Expected boot image/config",
    "red_flags": "Wrong image or boot variable",
    "likely_meaning": "Boot configuration issue",
    "next_command": "show version",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "boot,software",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-079",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Licensing",
    "subcategory": "License",
    "command": "show license",
    "command_mode": "EXEC",
    "purpose": "Shows licensing information where supported",
    "when_to_use": "Feature/license issue",
    "what_to_check": "License state and expiry",
    "healthy_indication": "Required feature licensed",
    "red_flags": "Expired/missing license",
    "likely_meaning": "Licensing entitlement/configuration issue",
    "next_command": "show version",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "license",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-080",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Logging",
    "subcategory": "Filtered Logs",
    "command": "show logging | include <text>",
    "command_mode": "EXEC",
    "purpose": "Filters log output for a keyword",
    "when_to_use": "Targeted event investigation",
    "what_to_check": "Matching timestamp/messages",
    "healthy_indication": "Relevant events around incident time",
    "red_flags": "Repeated errors/flaps/denials",
    "likely_meaning": "Correlate with interface/protocol events",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "logs,filter",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-081",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Interfaces",
    "subcategory": "Interface Config",
    "command": "show running-config interface <interface>",
    "command_mode": "EXEC",
    "purpose": "Shows configuration for one interface",
    "when_to_use": "Verify port configuration",
    "what_to_check": "Mode, VLAN, IP, speed, ACL, QoS",
    "healthy_indication": "Matches intended design",
    "red_flags": "Wrong/missing commands",
    "likely_meaning": "Interface configuration mismatch",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,configuration",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-082",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Routing",
    "subcategory": "Static Routes",
    "command": "show running-config | include ^ip route",
    "command_mode": "EXEC",
    "purpose": "Finds configured IPv4 static routes",
    "when_to_use": "Static route troubleshooting",
    "what_to_check": "Destination, mask, next-hop/interface",
    "healthy_indication": "Expected static route exists",
    "red_flags": "Missing/wrong/duplicate route",
    "likely_meaning": "Static routing configuration issue",
    "next_command": "show ip route",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "static-route,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-083",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Routing",
    "subcategory": "Default Route",
    "command": "show ip route 0.0.0.0",
    "command_mode": "EXEC",
    "purpose": "Checks the IPv4 default route",
    "when_to_use": "Internet/off-net reachability issue",
    "what_to_check": "Default route and next-hop",
    "healthy_indication": "Expected default route installed",
    "red_flags": "No default or unexpected next-hop",
    "likely_meaning": "Default routing issue",
    "next_command": "show ip route",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "default-route,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-084",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "IPv6 Route",
    "command": "show ipv6 route",
    "command_mode": "EXEC",
    "purpose": "Displays IPv6 routing table",
    "when_to_use": "IPv6 reachability issue",
    "what_to_check": "IPv6 routes and next-hops",
    "healthy_indication": "Expected IPv6 route",
    "red_flags": "Missing/wrong route",
    "likely_meaning": "IPv6 routing issue",
    "next_command": "show ipv6 interface brief",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ipv6,routing",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-085",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Layer3",
    "subcategory": "IPv6 Interface",
    "command": "show ipv6 interface brief",
    "command_mode": "EXEC",
    "purpose": "Quick IPv6 interface state",
    "when_to_use": "IPv6 interface problem",
    "what_to_check": "IPv6 addresses/status",
    "healthy_indication": "Expected addresses and up/up",
    "red_flags": "Missing address or down interface",
    "likely_meaning": "IPv6 interface/configuration issue",
    "next_command": "show ipv6 interface <interface>",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ipv6,interface",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-086",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Discovery",
    "subcategory": "CDP Summary",
    "command": "show cdp neighbors",
    "command_mode": "EXEC",
    "purpose": "Quick Cisco neighbor map",
    "when_to_use": "Physical topology check",
    "what_to_check": "Local port, neighbor, remote port",
    "healthy_indication": "Expected neighbor topology",
    "red_flags": "Missing/unexpected neighbor",
    "likely_meaning": "Link/CDP/topology issue",
    "next_command": "show cdp neighbors detail",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "cdp,topology",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-087",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Discovery",
    "subcategory": "LLDP Summary",
    "command": "show lldp neighbors",
    "command_mode": "EXEC",
    "purpose": "Quick LLDP neighbor map",
    "when_to_use": "Multi-vendor topology check",
    "what_to_check": "Local/remote port and chassis",
    "healthy_indication": "Expected neighbor topology",
    "red_flags": "Missing/unexpected neighbor",
    "likely_meaning": "Link/LLDP/topology issue",
    "next_command": "show lldp neighbors detail",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "lldp,topology",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-088",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "Native VLAN",
    "command": "show interfaces <interface> switchport",
    "command_mode": "EXEC",
    "purpose": "Checks native/access/trunk VLAN parameters",
    "when_to_use": "VLAN mismatch or native VLAN issue",
    "what_to_check": "Native VLAN and operational mode",
    "healthy_indication": "Matches design/peer",
    "red_flags": "Native VLAN mismatch",
    "likely_meaning": "Trunk/native VLAN issue",
    "next_command": "show interfaces trunk",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "native-vlan,trunk",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-089",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "STP",
    "subcategory": "Root Check",
    "command": "show spanning-tree root",
    "command_mode": "EXEC",
    "purpose": "Summarises STP root information",
    "when_to_use": "Verify root bridge",
    "what_to_check": "Root bridge and root port",
    "healthy_indication": "Expected root",
    "red_flags": "Unexpected root",
    "likely_meaning": "STP priority/topology issue",
    "next_command": "show spanning-tree vlan <vlan>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "stp,root",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-090",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch",
    "category": "Layer2",
    "subcategory": "Interface Counters Clear Check",
    "command": "show interfaces <interface> | include rate|drops|errors|CRC",
    "command_mode": "EXEC",
    "purpose": "Quickly extracts key counters from an interface",
    "when_to_use": "Fast triage",
    "what_to_check": "Rates, drops, errors, CRC",
    "healthy_indication": "Stable/expected counters",
    "red_flags": "Errors/drops increasing",
    "likely_meaning": "Physical/congestion issue",
    "next_command": "show interfaces <interface>",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "interface,triage",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-091",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Configuration",
    "subcategory": "Config Diff",
    "command": "show archive config differences nvram:startup-config system:running-config",
    "command_mode": "EXEC",
    "purpose": "Shows configuration differences where supported",
    "when_to_use": "Find unsaved changes",
    "what_to_check": "Changed lines",
    "healthy_indication": "No unexpected changes",
    "red_flags": "Unexpected pending changes",
    "likely_meaning": "Configuration drift",
    "next_command": "show running-config",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "config-diff",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-092",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Configuration",
    "subcategory": "Config Archive",
    "command": "show archive",
    "command_mode": "EXEC",
    "purpose": "Shows archived configurations where configured",
    "when_to_use": "Change investigation/rollback context",
    "what_to_check": "Archive entries and timestamps",
    "healthy_indication": "Expected change history",
    "red_flags": "Missing/old archive",
    "likely_meaning": "Change-management/backup issue",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "config,archive",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-093",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "System",
    "subcategory": "Clock",
    "command": "show clock",
    "command_mode": "EXEC",
    "purpose": "Shows device time",
    "when_to_use": "Correlate logs/events",
    "what_to_check": "Current date/time/timezone",
    "healthy_indication": "Correct time",
    "red_flags": "Wrong clock/timezone",
    "likely_meaning": "Log correlation/NTP issue",
    "next_command": "show ntp status",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "time,logs",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-094",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "System",
    "subcategory": "NTP Status",
    "command": "show ntp status",
    "command_mode": "EXEC",
    "purpose": "Shows NTP synchronisation status",
    "when_to_use": "Timestamp/NTP issue",
    "what_to_check": "Clock state, stratum, reference",
    "healthy_indication": "Synchronized",
    "red_flags": "Unsynchronized/stratum problems",
    "likely_meaning": "NTP reachability/configuration issue",
    "next_command": "show ntp associations",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "ntp,time",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-095",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "System",
    "subcategory": "NTP Associations",
    "command": "show ntp associations",
    "command_mode": "EXEC",
    "purpose": "Shows NTP peers/servers",
    "when_to_use": "NTP source troubleshooting",
    "what_to_check": "Reachability, selection, offset",
    "healthy_indication": "Expected peer selected",
    "red_flags": "Unreachable/no selection/high offset",
    "likely_meaning": "NTP reachability/configuration issue",
    "next_command": "show ntp status",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "ntp",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-096",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "System",
    "subcategory": "Users",
    "command": "show users",
    "command_mode": "EXEC",
    "purpose": "Shows current management sessions",
    "when_to_use": "Unexpected access/session issue",
    "what_to_check": "User lines, source, idle time",
    "healthy_indication": "Expected sessions",
    "red_flags": "Unexpected session",
    "likely_meaning": "Management/security investigation",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "management,security",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-097",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "System",
    "subcategory": "Line Status",
    "command": "show line",
    "command_mode": "EXEC",
    "purpose": "Shows console/VTY line state",
    "when_to_use": "Management access issue",
    "what_to_check": "Line state and configuration",
    "healthy_indication": "Expected VTY availability",
    "red_flags": "Unexpected busy/stuck line",
    "likely_meaning": "Management session/configuration issue",
    "next_command": "show users",
    "risk": "Safe",
    "difficulty": "Intermediate",
    "tags": "management,vty",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-098",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "System",
    "subcategory": "Tech Support",
    "command": "show tech-support",
    "command_mode": "EXEC",
    "purpose": "Collects broad troubleshooting information",
    "when_to_use": "Vendor TAC/major incident evidence",
    "what_to_check": "Large diagnostic output",
    "healthy_indication": "Collected during controlled window",
    "red_flags": "Very large output/CPU/storage impact",
    "likely_meaning": "Use selectively for escalation",
    "next_command": "show version",
    "risk": "Caution",
    "difficulty": "Advanced",
    "tags": "tac,diagnostics",
    "notes": "Can generate very large output; prefer targeted commands first."
  },
  {
    "id": "CIS-IOSXE-099",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Diagnostics",
    "subcategory": "Terminal Monitor",
    "command": "terminal monitor",
    "command_mode": "EXEC",
    "purpose": "Displays syslog messages on VTY session",
    "when_to_use": "Watch events during live troubleshooting",
    "what_to_check": "Real-time log messages",
    "healthy_indication": "Expected event visibility",
    "red_flags": "Large/noisy log stream",
    "likely_meaning": "Useful for correlating live events",
    "next_command": "terminal no monitor",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "logs,live-troubleshooting",
    "notes": ""
  },
  {
    "id": "CIS-IOSXE-100",
    "vendor": "Cisco",
    "platform": "IOS/IOS-XE",
    "os_version_scope": "IOS/IOS-XE",
    "device_type": "Switch/Router",
    "category": "Diagnostics",
    "subcategory": "Terminal Monitor Off",
    "command": "terminal no monitor",
    "command_mode": "EXEC",
    "purpose": "Stops live syslog display on VTY",
    "when_to_use": "After live log monitoring",
    "what_to_check": "No further logs displayed",
    "healthy_indication": "Quiet terminal",
    "red_flags": "Unexpected ongoing log stream",
    "likely_meaning": "Session output issue",
    "next_command": "show logging",
    "risk": "Safe",
    "difficulty": "Beginner",
    "tags": "logs,safety",
    "notes": ""
  }
];
