CREATE TABLE public.practice_questions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  category text NOT NULL CHECK (category IN ('CCNA','CCNP','Interview')),
  question_text text NOT NULL,
  options jsonb NOT NULL CHECK (jsonb_typeof(options) = 'array' AND jsonb_array_length(options) = 4),
  correct_option text NOT NULL,
  explanation text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT correct_in_options CHECK (options ? correct_option)
);
CREATE INDEX practice_questions_category_idx ON public.practice_questions(category);
GRANT SELECT ON public.practice_questions TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.practice_questions TO authenticated;
GRANT ALL ON public.practice_questions TO service_role;
ALTER TABLE public.practice_questions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "practice questions public read" ON public.practice_questions FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "practice questions admin insert" ON public.practice_questions FOR INSERT TO authenticated WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "practice questions admin update" ON public.practice_questions FOR UPDATE TO authenticated USING (public.has_role(auth.uid(),'admin')) WITH CHECK (public.has_role(auth.uid(),'admin'));
CREATE POLICY "practice questions admin delete" ON public.practice_questions FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));

CREATE OR REPLACE FUNCTION public.get_random_practice_questions(_category text, _limit int DEFAULT 10)
RETURNS SETOF public.practice_questions
LANGUAGE sql VOLATILE SECURITY INVOKER SET search_path = public
AS $$
  SELECT * FROM public.practice_questions WHERE category = _category ORDER BY random() LIMIT LEAST(GREATEST(_limit,1),50);
$$;
GRANT EXECUTE ON FUNCTION public.get_random_practice_questions(text,int) TO anon, authenticated;

INSERT INTO public.practice_questions (category, question_text, options, correct_option, explanation) VALUES
('CCNA','Which OSI layer is responsible for logical addressing and routing?','["Data Link","Network","Transport","Session"]','Network','Layer 3 (Network) handles logical addressing (IP) and path selection between networks. Layer 2 uses MAC addresses within a single segment.'),
('CCNA','How many usable host addresses are in a /26 subnet?','["30","62","64","126"]','62','A /26 leaves 6 host bits: 2^6 = 64 addresses, minus the network and broadcast addresses = 62 usable hosts.'),
('CCNA','What is the default administrative distance of OSPF?','["90","100","110","120"]','110','Cisco default ADs: EIGRP internal 90, OSPF 110, IS-IS 115, RIP 120. Lower AD is preferred when the same prefix is learned from multiple sources.'),
('CCNA','Which protocol does a switch use to prevent Layer 2 loops?','["VTP","STP","CDP","HSRP"]','STP','Spanning Tree Protocol (802.1D) blocks redundant ports so there is only one active path, preventing broadcast storms and MAC table instability.'),
('CCNA','Which command shows the MAC address table on a Cisco switch?','["show ip route","show mac address-table","show arp","show interfaces trunk"]','show mac address-table','show mac address-table lists learned MAC addresses with their VLAN and port. show arp maps IP to MAC at Layer 3.'),
('CCNA','What is the range of private addresses in the Class B RFC 1918 block?','["172.16.0.0 - 172.31.255.255","172.16.0.0 - 172.16.255.255","169.254.0.0 - 169.254.255.255","192.168.0.0 - 192.168.255.255"]','172.16.0.0 - 172.31.255.255','RFC 1918 reserves 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16. The /12 spans 172.16.0.0 to 172.31.255.255. 169.254/16 is APIPA link-local.'),
('CCNA','Which trunking protocol is the IEEE standard?','["ISL","802.1Q","802.1X","802.3ad"]','802.1Q','802.1Q inserts a 4-byte tag carrying the VLAN ID. ISL is Cisco-proprietary and deprecated; 802.1X is port authentication; 802.3ad is LACP.'),
('CCNA','What port does SSH use by default?','["21","22","23","443"]','22','SSH uses TCP 22. Telnet uses TCP 23 and sends credentials in cleartext, which is why SSH is preferred for device management.'),
('CCNA','Which DHCP message does a client send first?','["Offer","Request","Discover","Acknowledge"]','Discover','DHCP follows DORA: Discover (client broadcast), Offer (server), Request (client), Acknowledge (server).'),
('CCNA','In the wildcard mask 0.0.0.255, which octet bits are ignored?','["First octet","Second octet","Third octet","Fourth octet"]','Fourth octet','In wildcard masks, a 1 bit means "ignore". 0.0.0.255 matches the first three octets exactly and ignores the last octet, like a /24.'),
('CCNA','What does NAT overload (PAT) use to distinguish sessions?','["MAC addresses","Source port numbers","VLAN IDs","TTL values"]','Source port numbers','PAT maps many inside hosts to one public IP by tracking unique source port numbers for each translation.'),
('CCNA','Which IPv6 address type begins with FE80::/10?','["Global unicast","Unique local","Link-local","Multicast"]','Link-local','FE80::/10 is link-local, automatically configured on every IPv6 interface and not routed. FC00::/7 is unique local, FF00::/8 is multicast.'),
('CCNP','Which BGP attribute is evaluated first in the Cisco best-path selection?','["Local Preference","Weight","AS Path length","MED"]','Weight','Cisco evaluates Weight first (Cisco-proprietary, local to the router), then Local Preference, locally originated, AS Path length, Origin, then MED.'),
('CCNP','Which OSPF LSA type is generated by an ABR to advertise inter-area routes?','["Type 1","Type 2","Type 3","Type 5"]','Type 3','Type 3 Summary LSAs are generated by ABRs for inter-area prefixes. Type 1 = router, Type 2 = network (DR), Type 5 = external from an ASBR.'),
('CCNP','What is the default EIGRP K-value combination used in the metric?','["K1 and K3","K1 and K2","K2 and K4","K4 and K5"]','K1 and K3','By default K1 (bandwidth) = 1 and K3 (delay) = 1; K2, K4 and K5 are 0, so the metric uses only bandwidth and delay.'),
('CCNP','Which protocol provides first-hop redundancy with load balancing across multiple active gateways?','["HSRP","VRRP","GLBP","CARP"]','GLBP','GLBP uses an AVG to hand out different virtual MACs to hosts so multiple AVFs forward traffic simultaneously. HSRP and VRRP have one active forwarder per group.'),
('CCNP','What is the purpose of a route distinguisher in MPLS L3VPN?','["Control route import/export","Make overlapping customer prefixes unique","Label switch packets","Select best path"]','Make overlapping customer prefixes unique','The RD is prepended to IPv4 prefixes to form VPNv4 routes so identical customer prefixes stay unique in MP-BGP. Route targets control import/export.'),
('CCNP','Which STP enhancement immediately err-disables a PortFast port that receives a BPDU?','["Root Guard","BPDU Guard","Loop Guard","BPDU Filter"]','BPDU Guard','BPDU Guard shuts down edge ports that receive BPDUs, preventing rogue switches. Root Guard only blocks superior BPDUs; Loop Guard protects against unidirectional failures.'),
('CCNP','In BGP, which state indicates the TCP session is established and routes can be exchanged?','["Active","OpenSent","OpenConfirm","Established"]','Established','BGP FSM: Idle, Connect, Active, OpenSent, OpenConfirm, Established. Only in Established are UPDATE messages exchanged. Stuck in Active usually means TCP is failing.'),
('CCNP','Which OSPF area type blocks Type 5 LSAs but allows Type 7?','["Stub","Totally stubby","NSSA","Backbone"]','NSSA','A Not-So-Stubby Area blocks Type 5 externals but lets a local ASBR inject externals as Type 7, which the ABR translates to Type 5.'),
('CCNP','What does VXLAN use to identify a Layer 2 segment?','["12-bit VLAN ID","24-bit VNI","20-bit MPLS label","16-bit SGT"]','24-bit VNI','VXLAN encapsulates Ethernet in UDP (port 4789) and uses a 24-bit VXLAN Network Identifier, allowing about 16 million segments vs 4094 VLANs.'),
('CCNP','Which QoS mechanism drops packets early to avoid TCP global synchronization?','["LLQ","WRED","CBWFQ","Policing"]','WRED','Weighted Random Early Detection randomly drops packets as queue depth grows, so TCP flows back off at different times instead of all at once.'),
('CCNP','Which command enables uRPF strict mode on a Cisco interface?','["ip verify unicast source reachable-via any","ip verify unicast source reachable-via rx","ip cef strict","ip urpf enable"]','ip verify unicast source reachable-via rx','Strict uRPF (rx) requires the source to be reachable via the receiving interface. Loose mode (any) only requires a route to exist.'),
('CCNP','What is the default BGP keepalive and hold timer on Cisco IOS?','["10s / 30s","30s / 90s","60s / 180s","5s / 15s"]','60s / 180s','Cisco IOS defaults to a 60 second keepalive and 180 second hold time. Peers negotiate the lower hold time during OPEN.'),
('Interview','A user reports they can reach websites by IP but not by name. What is the most likely cause?','["Bad default gateway","DNS resolution failure","Duplex mismatch","STP blocking"]','DNS resolution failure','If IP connectivity works but names fail, routing is fine and the problem is name resolution: wrong DNS server, blocked UDP/TCP 53, or a failed resolver.'),
('Interview','What is the first thing you check when a host gets a 169.254.x.x address?','["DNS settings","DHCP reachability","BGP neighbors","Firewall NAT rules"]','DHCP reachability','169.254/16 is APIPA, self-assigned when no DHCP server responds. Check the link, VLAN, DHCP relay (ip helper-address) and scope exhaustion.'),
('Interview','Explain the difference between TCP and UDP. Which statement is correct?','["UDP guarantees delivery","TCP is connectionless","TCP provides ordered, reliable delivery; UDP does not","UDP uses a three-way handshake"]','TCP provides ordered, reliable delivery; UDP does not','TCP is connection-oriented with a handshake, sequencing, acknowledgements and retransmission. UDP is connectionless and lightweight, suited to voice, video and DNS.'),
('Interview','Traceroute shows asterisks at one hop but completes to the destination. What does it mean?','["The path is broken","That hop rate-limits or filters ICMP replies","DNS is failing","The destination is down"]','That hop rate-limits or filters ICMP replies','A silent hop that still forwards traffic usually deprioritises or filters ICMP time-exceeded messages. If later hops respond, forwarding works.'),
('Interview','What is the difference between a switch and a router?','["Switches forward by IP, routers by MAC","Switches forward within a LAN using MAC; routers forward between networks using IP","They are identical","Routers cannot run VLANs"]','Switches forward within a LAN using MAC; routers forward between networks using IP','Layer 2 switches build MAC tables to forward frames within a broadcast domain. Routers use IP routing tables to move packets between networks.'),
('Interview','Users on one VLAN cannot reach another VLAN, but hosts within each VLAN work. What is missing?','["Inter-VLAN routing","A new DHCP scope","STP root bridge","Port security"]','Inter-VLAN routing','VLANs are separate broadcast domains; traffic between them needs a Layer 3 device (router-on-a-stick or SVIs on a multilayer switch) and correct gateways.'),
('Interview','What does a high number of CRC errors on an interface usually indicate?','["Routing loop","Physical layer problem such as cabling or duplex","DNS misconfiguration","ACL denying traffic"]','Physical layer problem such as cabling or duplex','CRC errors mean frames arrived corrupted: bad cables, interference, faulty optics or a duplex mismatch. Start at Layer 1.'),
('Interview','Which tool would you use to capture packets for deep troubleshooting?','["Wireshark","nslookup","ipconfig","ping"]','Wireshark','Wireshark (or tcpdump) captures and decodes packets, letting you see handshakes, retransmissions and protocol errors that simple tools cannot.'),
('Interview','What is the purpose of a default gateway on a host?','["Resolve names","Forward traffic destined outside the local subnet","Assign IP addresses","Encrypt traffic"]','Forward traffic destined outside the local subnet','Hosts send traffic for non-local destinations to the default gateway, usually the router interface on their subnet.'),
('Interview','How would you describe a subnet mask of 255.255.255.0 in CIDR notation?','["/16","/24","/28","/32"]','/24','255.255.255.0 has 24 network bits set to 1, so it is /24 with 256 addresses and 254 usable hosts.'),
('Interview','An application is slow only for remote-office users over a VPN. What should you investigate first?','["MTU and fragmentation over the tunnel","The local printer","STP priority","Switch port colour"]','MTU and fragmentation over the tunnel','VPN encapsulation reduces effective MTU. Oversized packets get fragmented or dropped (especially if ICMP is blocked), causing slowness. Check MSS clamping and latency.'),
('Interview','What does ARP do?','["Maps IP addresses to MAC addresses","Maps names to IPs","Assigns IP addresses","Routes between networks"]','Maps IP addresses to MAC addresses','ARP broadcasts "who has this IP?" on the local segment and caches the MAC reply so frames can be delivered at Layer 2.');