/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoisipRouteImport } from './routes/whoisip'
import { Route as TracerouteRouteImport } from './routes/traceroute'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubnetRouteImport } from './routes/subnet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PortcheckRouteImport } from './routes/portcheck'
import { Route as PingipRouteImport } from './routes/pingip'
import { Route as PingRouteImport } from './routes/ping'
import { Route as MonitoringRouteImport } from './routes/monitoring'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as DnslookupRouteImport } from './routes/dnslookup'
import { Route as CyberNewsRouteImport } from './routes/cyber-news'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlacklistRouteImport } from './routes/blacklist'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApPlanningRouteImport } from './routes/ap-planning'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyLesson9RouteImport } from './routes/academy.lesson-9'
import { Route as AcademyLesson8RouteImport } from './routes/academy.lesson-8'
import { Route as AcademyLesson7RouteImport } from './routes/academy.lesson-7'
import { Route as AcademyLesson6RouteImport } from './routes/academy.lesson-6'
import { Route as AcademyLesson5RouteImport } from './routes/academy.lesson-5'
import { Route as AcademyLesson4RouteImport } from './routes/academy.lesson-4'
import { Route as AcademyLesson3RouteImport } from './routes/academy.lesson-3'
import { Route as AcademyLesson2RouteImport } from './routes/academy.lesson-2'
import { Route as AcademyLesson1RouteImport } from './routes/academy.lesson-1'
import { Route as ApiPublicUploadRouteImport } from './routes/api/public/upload'
import { Route as ApiPublicHooksMonitorTickRouteImport } from './routes/api/public/hooks/monitor-tick'

const WhoisipRoute = WhoisipRouteImport.update({
  id: '/whoisip',
  path: '/whoisip',
  getParentRoute: () => rootRouteImport,
} as any)
const TracerouteRoute = TracerouteRouteImport.update({
  id: '/traceroute',
  path: '/traceroute',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubnetRoute = SubnetRouteImport.update({
  id: '/subnet',
  path: '/subnet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortcheckRoute = PortcheckRouteImport.update({
  id: '/portcheck',
  path: '/portcheck',
  getParentRoute: () => rootRouteImport,
} as any)
const PingipRoute = PingipRouteImport.update({
  id: '/pingip',
  path: '/pingip',
  getParentRoute: () => rootRouteImport,
} as any)
const PingRoute = PingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoringRoute = MonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const DnslookupRoute = DnslookupRouteImport.update({
  id: '/dnslookup',
  path: '/dnslookup',
  getParentRoute: () => rootRouteImport,
} as any)
const CyberNewsRoute = CyberNewsRouteImport.update({
  id: '/cyber-news',
  path: '/cyber-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlacklistRoute = BlacklistRouteImport.update({
  id: '/blacklist',
  path: '/blacklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApPlanningRoute = ApPlanningRouteImport.update({
  id: '/ap-planning',
  path: '/ap-planning',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson9Route = AcademyLesson9RouteImport.update({
  id: '/lesson-9',
  path: '/lesson-9',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson8Route = AcademyLesson8RouteImport.update({
  id: '/lesson-8',
  path: '/lesson-8',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson7Route = AcademyLesson7RouteImport.update({
  id: '/lesson-7',
  path: '/lesson-7',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson6Route = AcademyLesson6RouteImport.update({
  id: '/lesson-6',
  path: '/lesson-6',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson5Route = AcademyLesson5RouteImport.update({
  id: '/lesson-5',
  path: '/lesson-5',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson4Route = AcademyLesson4RouteImport.update({
  id: '/lesson-4',
  path: '/lesson-4',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson3Route = AcademyLesson3RouteImport.update({
  id: '/lesson-3',
  path: '/lesson-3',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson2Route = AcademyLesson2RouteImport.update({
  id: '/lesson-2',
  path: '/lesson-2',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLesson1Route = AcademyLesson1RouteImport.update({
  id: '/lesson-1',
  path: '/lesson-1',
  getParentRoute: () => AcademyRoute,
} as any)
const ApiPublicUploadRoute = ApiPublicUploadRouteImport.update({
  id: '/api/public/upload',
  path: '/api/public/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMonitorTickRoute =
  ApiPublicHooksMonitorTickRouteImport.update({
    id: '/api/public/hooks/monitor-tick',
    path: '/api/public/hooks/monitor-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/ap-planning': typeof ApPlanningRoute
  '/auth': typeof AuthRoute
  '/blacklist': typeof BlacklistRoute
  '/contact': typeof ContactRoute
  '/cyber-news': typeof CyberNewsRoute
  '/dnslookup': typeof DnslookupRoute
  '/global': typeof GlobalRoute
  '/monitoring': typeof MonitoringRoute
  '/ping': typeof PingRoute
  '/pingip': typeof PingipRoute
  '/portcheck': typeof PortcheckRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subnet': typeof SubnetRoute
  '/terms': typeof TermsRoute
  '/traceroute': typeof TracerouteRoute
  '/whoisip': typeof WhoisipRoute
  '/academy/what-is-a-computer-network': typeof AcademyLesson1Route
  '/academy/lan-wan-man-pan': typeof AcademyLesson2Route
  '/academy/ip-addressing': typeof AcademyLesson3Route
  '/academy/ipv4-address-classes': typeof AcademyLesson4Route
  '/academy/public-vs-private-ip': typeof AcademyLesson5Route
  '/academy/subnetting': typeof AcademyLesson6Route
  '/academy/subnet-masks': typeof AcademyLesson7Route
  '/academy/cidr-notation': typeof AcademyLesson8Route
  '/academy/network-broadcast-usable-ip': typeof AcademyLesson9Route
  '/academy/': typeof AcademyIndexRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/hooks/monitor-tick': typeof ApiPublicHooksMonitorTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ap-planning': typeof ApPlanningRoute
  '/auth': typeof AuthRoute
  '/blacklist': typeof BlacklistRoute
  '/contact': typeof ContactRoute
  '/cyber-news': typeof CyberNewsRoute
  '/dnslookup': typeof DnslookupRoute
  '/global': typeof GlobalRoute
  '/monitoring': typeof MonitoringRoute
  '/ping': typeof PingRoute
  '/pingip': typeof PingipRoute
  '/portcheck': typeof PortcheckRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subnet': typeof SubnetRoute
  '/terms': typeof TermsRoute
  '/traceroute': typeof TracerouteRoute
  '/whoisip': typeof WhoisipRoute
  '/academy/what-is-a-computer-network': typeof AcademyLesson1Route
  '/academy/lan-wan-man-pan': typeof AcademyLesson2Route
  '/academy/ip-addressing': typeof AcademyLesson3Route
  '/academy/ipv4-address-classes': typeof AcademyLesson4Route
  '/academy/public-vs-private-ip': typeof AcademyLesson5Route
  '/academy/subnetting': typeof AcademyLesson6Route
  '/academy/subnet-masks': typeof AcademyLesson7Route
  '/academy/cidr-notation': typeof AcademyLesson8Route
  '/academy/network-broadcast-usable-ip': typeof AcademyLesson9Route
  '/academy': typeof AcademyIndexRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/hooks/monitor-tick': typeof ApiPublicHooksMonitorTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/ap-planning': typeof ApPlanningRoute
  '/auth': typeof AuthRoute
  '/blacklist': typeof BlacklistRoute
  '/contact': typeof ContactRoute
  '/cyber-news': typeof CyberNewsRoute
  '/dnslookup': typeof DnslookupRoute
  '/global': typeof GlobalRoute
  '/monitoring': typeof MonitoringRoute
  '/ping': typeof PingRoute
  '/pingip': typeof PingipRoute
  '/portcheck': typeof PortcheckRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subnet': typeof SubnetRoute
  '/terms': typeof TermsRoute
  '/traceroute': typeof TracerouteRoute
  '/whoisip': typeof WhoisipRoute
  '/academy/what-is-a-computer-network': typeof AcademyLesson1Route
  '/academy/lan-wan-man-pan': typeof AcademyLesson2Route
  '/academy/ip-addressing': typeof AcademyLesson3Route
  '/academy/ipv4-address-classes': typeof AcademyLesson4Route
  '/academy/public-vs-private-ip': typeof AcademyLesson5Route
  '/academy/subnetting': typeof AcademyLesson6Route
  '/academy/subnet-masks': typeof AcademyLesson7Route
  '/academy/cidr-notation': typeof AcademyLesson8Route
  '/academy/network-broadcast-usable-ip': typeof AcademyLesson9Route
  '/academy/': typeof AcademyIndexRoute
  '/api/public/upload': typeof ApiPublicUploadRoute
  '/api/public/hooks/monitor-tick': typeof ApiPublicHooksMonitorTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/ap-planning'
    | '/auth'
    | '/blacklist'
    | '/contact'
    | '/cyber-news'
    | '/dnslookup'
    | '/global'
    | '/monitoring'
    | '/ping'
    | '/pingip'
    | '/portcheck'
    | '/privacy'
    | '/sitemap.xml'
    | '/subnet'
    | '/terms'
    | '/traceroute'
    | '/whoisip'
    | '/academy/what-is-a-computer-network'
    | '/academy/lan-wan-man-pan'
    | '/academy/ip-addressing'
    | '/academy/ipv4-address-classes'
    | '/academy/public-vs-private-ip'
    | '/academy/subnetting'
    | '/academy/subnet-masks'
    | '/academy/cidr-notation'
    | '/academy/network-broadcast-usable-ip'
    | '/academy/'
    | '/api/public/upload'
    | '/api/public/hooks/monitor-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ap-planning'
    | '/auth'
    | '/blacklist'
    | '/contact'
    | '/cyber-news'
    | '/dnslookup'
    | '/global'
    | '/monitoring'
    | '/ping'
    | '/pingip'
    | '/portcheck'
    | '/privacy'
    | '/sitemap.xml'
    | '/subnet'
    | '/terms'
    | '/traceroute'
    | '/whoisip'
    | '/academy/what-is-a-computer-network'
    | '/academy/lan-wan-man-pan'
    | '/academy/ip-addressing'
    | '/academy/ipv4-address-classes'
    | '/academy/public-vs-private-ip'
    | '/academy/subnetting'
    | '/academy/subnet-masks'
    | '/academy/cidr-notation'
    | '/academy/network-broadcast-usable-ip'
    | '/academy'
    | '/api/public/upload'
    | '/api/public/hooks/monitor-tick'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/ap-planning'
    | '/auth'
    | '/blacklist'
    | '/contact'
    | '/cyber-news'
    | '/dnslookup'
    | '/global'
    | '/monitoring'
    | '/ping'
    | '/pingip'
    | '/portcheck'
    | '/privacy'
    | '/sitemap.xml'
    | '/subnet'
    | '/terms'
    | '/traceroute'
    | '/whoisip'
    | '/academy/what-is-a-computer-network'
    | '/academy/lan-wan-man-pan'
    | '/academy/ip-addressing'
    | '/academy/ipv4-address-classes'
    | '/academy/public-vs-private-ip'
    | '/academy/subnetting'
    | '/academy/subnet-masks'
    | '/academy/cidr-notation'
    | '/academy/network-broadcast-usable-ip'
    | '/academy/'
    | '/api/public/upload'
    | '/api/public/hooks/monitor-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  ApPlanningRoute: typeof ApPlanningRoute
  AuthRoute: typeof AuthRoute
  BlacklistRoute: typeof BlacklistRoute
  ContactRoute: typeof ContactRoute
  CyberNewsRoute: typeof CyberNewsRoute
  DnslookupRoute: typeof DnslookupRoute
  GlobalRoute: typeof GlobalRoute
  MonitoringRoute: typeof MonitoringRoute
  PingRoute: typeof PingRoute
  PingipRoute: typeof PingipRoute
  PortcheckRoute: typeof PortcheckRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubnetRoute: typeof SubnetRoute
  TermsRoute: typeof TermsRoute
  TracerouteRoute: typeof TracerouteRoute
  WhoisipRoute: typeof WhoisipRoute
  ApiPublicUploadRoute: typeof ApiPublicUploadRoute
  ApiPublicHooksMonitorTickRoute: typeof ApiPublicHooksMonitorTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whoisip': {
      id: '/whoisip'
      path: '/whoisip'
      fullPath: '/whoisip'
      preLoaderRoute: typeof WhoisipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceroute': {
      id: '/traceroute'
      path: '/traceroute'
      fullPath: '/traceroute'
      preLoaderRoute: typeof TracerouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subnet': {
      id: '/subnet'
      path: '/subnet'
      fullPath: '/subnet'
      preLoaderRoute: typeof SubnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portcheck': {
      id: '/portcheck'
      path: '/portcheck'
      fullPath: '/portcheck'
      preLoaderRoute: typeof PortcheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pingip': {
      id: '/pingip'
      path: '/pingip'
      fullPath: '/pingip'
      preLoaderRoute: typeof PingipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ping': {
      id: '/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoring': {
      id: '/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof MonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dnslookup': {
      id: '/dnslookup'
      path: '/dnslookup'
      fullPath: '/dnslookup'
      preLoaderRoute: typeof DnslookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cyber-news': {
      id: '/cyber-news'
      path: '/cyber-news'
      fullPath: '/cyber-news'
      preLoaderRoute: typeof CyberNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blacklist': {
      id: '/blacklist'
      path: '/blacklist'
      fullPath: '/blacklist'
      preLoaderRoute: typeof BlacklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ap-planning': {
      id: '/ap-planning'
      path: '/ap-planning'
      fullPath: '/ap-planning'
      preLoaderRoute: typeof ApPlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/network-broadcast-usable-ip': {
      id: '/academy/network-broadcast-usable-ip'
      path: '/lesson-9'
      fullPath: '/academy/network-broadcast-usable-ip'
      preLoaderRoute: typeof AcademyLesson9RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/cidr-notation': {
      id: '/academy/cidr-notation'
      path: '/lesson-8'
      fullPath: '/academy/cidr-notation'
      preLoaderRoute: typeof AcademyLesson8RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/subnet-masks': {
      id: '/academy/subnet-masks'
      path: '/lesson-7'
      fullPath: '/academy/subnet-masks'
      preLoaderRoute: typeof AcademyLesson7RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/subnetting': {
      id: '/academy/subnetting'
      path: '/lesson-6'
      fullPath: '/academy/subnetting'
      preLoaderRoute: typeof AcademyLesson6RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/public-vs-private-ip': {
      id: '/academy/public-vs-private-ip'
      path: '/lesson-5'
      fullPath: '/academy/public-vs-private-ip'
      preLoaderRoute: typeof AcademyLesson5RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/ipv4-address-classes': {
      id: '/academy/ipv4-address-classes'
      path: '/lesson-4'
      fullPath: '/academy/ipv4-address-classes'
      preLoaderRoute: typeof AcademyLesson4RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/ip-addressing': {
      id: '/academy/ip-addressing'
      path: '/lesson-3'
      fullPath: '/academy/ip-addressing'
      preLoaderRoute: typeof AcademyLesson3RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/lan-wan-man-pan': {
      id: '/academy/lan-wan-man-pan'
      path: '/lesson-2'
      fullPath: '/academy/lan-wan-man-pan'
      preLoaderRoute: typeof AcademyLesson2RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/what-is-a-computer-network': {
      id: '/academy/what-is-a-computer-network'
      path: '/lesson-1'
      fullPath: '/academy/what-is-a-computer-network'
      preLoaderRoute: typeof AcademyLesson1RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/api/public/upload': {
      id: '/api/public/upload'
      path: '/api/public/upload'
      fullPath: '/api/public/upload'
      preLoaderRoute: typeof ApiPublicUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/monitor-tick': {
      id: '/api/public/hooks/monitor-tick'
      path: '/api/public/hooks/monitor-tick'
      fullPath: '/api/public/hooks/monitor-tick'
      preLoaderRoute: typeof ApiPublicHooksMonitorTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyRouteChildren {
  AcademyLesson1Route: typeof AcademyLesson1Route
  AcademyLesson2Route: typeof AcademyLesson2Route
  AcademyLesson3Route: typeof AcademyLesson3Route
  AcademyLesson4Route: typeof AcademyLesson4Route
  AcademyLesson5Route: typeof AcademyLesson5Route
  AcademyLesson6Route: typeof AcademyLesson6Route
  AcademyLesson7Route: typeof AcademyLesson7Route
  AcademyLesson8Route: typeof AcademyLesson8Route
  AcademyLesson9Route: typeof AcademyLesson9Route
  AcademyIndexRoute: typeof AcademyIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyLesson1Route: AcademyLesson1Route,
  AcademyLesson2Route: AcademyLesson2Route,
  AcademyLesson3Route: AcademyLesson3Route,
  AcademyLesson4Route: AcademyLesson4Route,
  AcademyLesson5Route: AcademyLesson5Route,
  AcademyLesson6Route: AcademyLesson6Route,
  AcademyLesson7Route: AcademyLesson7Route,
  AcademyLesson8Route: AcademyLesson8Route,
  AcademyLesson9Route: AcademyLesson9Route,
  AcademyIndexRoute: AcademyIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  ApPlanningRoute: ApPlanningRoute,
  AuthRoute: AuthRoute,
  BlacklistRoute: BlacklistRoute,
  ContactRoute: ContactRoute,
  CyberNewsRoute: CyberNewsRoute,
  DnslookupRoute: DnslookupRoute,
  GlobalRoute: GlobalRoute,
  MonitoringRoute: MonitoringRoute,
  PingRoute: PingRoute,
  PingipRoute: PingipRoute,
  PortcheckRoute: PortcheckRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubnetRoute: SubnetRoute,
  TermsRoute: TermsRoute,
  TracerouteRoute: TracerouteRoute,
  WhoisipRoute: WhoisipRoute,
  ApiPublicUploadRoute: ApiPublicUploadRoute,
  ApiPublicHooksMonitorTickRoute: ApiPublicHooksMonitorTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
